apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "eduhub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eduhub.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        {{- include "eduhub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.serviceName }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}/{{ .Values.serviceName }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: http
        envFrom:
        - secretRef:
            name: "{{ .Values.serviceName }}-secret"
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        {{- if not (and (hasKey .Values.livenessProbe "enabled") (not .Values.livenessProbe.enabled)) }}
        livenessProbe:
          {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 10 }}
        {{- end }}
        {{- if not (and (hasKey .Values.readinessProbe "enabled") (not .Values.readinessProbe.enabled)) }}
        readinessProbe:
          {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 10 }}
        {{- end }}